using CryptoCom.Net.Objects;
using CryptoCom.Net.Objects.Internal;
using CryptoCom.Net.Objects.Models;
using CryptoExchange.Net.Objects;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CryptoCom.Net.Converters
{
    [JsonSerializable(typeof(ParameterCollection))]
    [JsonSerializable(typeof(CryptoComResponse<object>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComListOrderResult>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComAnnouncementWrapper>))]
    // End manual defined attributes

    [JsonSerializable(typeof(CryptoComResponse<CryptoComSubscriptionEvent<CryptoComOrderBookUpdateInt[]>>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComSubscriptionEvent<CryptoComTicker[]>>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComSubscriptionEvent<CryptoComTrade[]>>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComSubscriptionEvent<CryptoComKline[]>>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComSubscriptionEvent<CryptoComValuation[]>>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComSubscriptionEvent<CryptoComOrder[]>>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComSubscriptionEvent<CryptoComUserTrade[]>>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComSubscriptionEvent<CryptoComBalances[]>>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComSubscriptionEvent<CryptoComPosition[]>>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComSubscriptionEvent<CryptoComBalancePositionUpdate[]>>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComAccountSettings[]>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComOrderResult[]>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComCancelOrderResult[]>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComBalancesWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComBalanceHistory>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComAccountInfo>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComTransactionWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComUserFee>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComSymbolFeeRate>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComWithdrawalResult>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComAssetWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComDepositAddressWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComDepositWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComWithdrawalWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComTickersWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComRiskParameters>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComSymbolWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComOrderBookWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComKlineWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComTradeWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComValuationWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComExpiredPriceWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComStakeResult>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComUnstakeResult>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComStakePositionWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComStakingSymbolWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComStakingRequestWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComStakingRewardWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComConvertResult>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComConvertRequestWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComConversionRate>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComPositionWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComOrderId>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComOrderWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComOrder>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComUserTradeWrapper>))]
    [JsonSerializable(typeof(CryptoComResponse<CryptoComOcoResult>))]
    [JsonSerializable(typeof(IDictionary<string, object>))]
    [JsonSerializable(typeof(CryptoComOrderId[]))]
    [JsonSerializable(typeof(CryptoComAccountInfo[]))]
    [JsonSerializable(typeof(CryptoComAccountDetails[]))]
    [JsonSerializable(typeof(CryptoComAssetWrapper[]))]
    [JsonSerializable(typeof(CryptoComAsset[]))]
    [JsonSerializable(typeof(CryptoComAssetNetwork[]))]
    [JsonSerializable(typeof(CryptoComBalanceHistory[]))]
    [JsonSerializable(typeof(CryptoComBalanceHistoryValue[]))]
    [JsonSerializable(typeof(CryptoComBalanceUpdate[]))]
    [JsonSerializable(typeof(CryptoComBalancesWrapper[]))]
    [JsonSerializable(typeof(CryptoComBalance[]))]
    [JsonSerializable(typeof(CryptoComCancelOrderRequest[]))]
    [JsonSerializable(typeof(CryptoComConversionRate[]))]
    [JsonSerializable(typeof(CryptoComConvertRequestWrapper[]))]
    [JsonSerializable(typeof(CryptoComConvertRequest[]))]
    [JsonSerializable(typeof(CryptoComConvertResult[]))]
    [JsonSerializable(typeof(CryptoComDepositWrapper[]))]
    [JsonSerializable(typeof(CryptoComDeposit[]))]
    [JsonSerializable(typeof(CryptoComDepositAddressWrapper[]))]
    [JsonSerializable(typeof(CryptoComDepositAddress[]))]
    [JsonSerializable(typeof(CryptoComExpiredPriceWrapper[]))]
    [JsonSerializable(typeof(CryptoComExpiredPrice[]))]
    [JsonSerializable(typeof(CryptoComKlineWrapper[]))]
    [JsonSerializable(typeof(CryptoComOcoResult[]))]
    [JsonSerializable(typeof(CryptoComOrderWrapper[]))]
    [JsonSerializable(typeof(CryptoComOrderBookWrapper[]))]
    [JsonSerializable(typeof(CryptoComOrderBook[]))]
    [JsonSerializable(typeof(CryptoComOrderBookUpdate[]))]
    [JsonSerializable(typeof(CryptoComOrderBookEntry[]))]
    [JsonSerializable(typeof(CryptoComOrderRequest[]))]
    [JsonSerializable(typeof(CryptoComPositionWrapper[]))]
    [JsonSerializable(typeof(CryptoComRiskParameters[]))]
    [JsonSerializable(typeof(CryptoComRiskParametersAsset[]))]
    [JsonSerializable(typeof(CryptoComStakePositionWrapper[]))]
    [JsonSerializable(typeof(CryptoComStakePosition[]))]
    [JsonSerializable(typeof(CryptoComStakeResult[]))]
    [JsonSerializable(typeof(CryptoComStakingRequestWrapper[]))]
    [JsonSerializable(typeof(CryptoComStakingRequest[]))]
    [JsonSerializable(typeof(CryptoComStakingRewardWrapper[]))]
    [JsonSerializable(typeof(CryptoComStakingReward[]))]
    [JsonSerializable(typeof(CryptoComStakingSymbolWrapper[]))]
    [JsonSerializable(typeof(CryptoComStakingSymbol[]))]
    [JsonSerializable(typeof(CryptoComSymbolWrapper[]))]
    [JsonSerializable(typeof(CryptoComSymbol[]))]
    [JsonSerializable(typeof(CryptoComSymbolFeeRate[]))]
    [JsonSerializable(typeof(CryptoComTickersWrapper[]))]
    [JsonSerializable(typeof(CryptoComTradeWrapper[]))]
    [JsonSerializable(typeof(CryptoComTransactionWrapper[]))]
    [JsonSerializable(typeof(CryptoComTransaction[]))]
    [JsonSerializable(typeof(CryptoComUnstakeResult[]))]
    [JsonSerializable(typeof(CryptoComUserFee[]))]
    [JsonSerializable(typeof(CryptoComUserTradeWrapper[]))]
    [JsonSerializable(typeof(CryptoComValuationWrapper[]))]
    [JsonSerializable(typeof(CryptoComWithdrawalWrapper[]))]
    [JsonSerializable(typeof(CryptoComWithdrawal[]))]
    [JsonSerializable(typeof(CryptoComWithdrawalResult[]))]
    [JsonSerializable(typeof(CryptoComResponse))]
    [JsonSerializable(typeof(CryptoComRequest))]
    [JsonSerializable(typeof(string))]
    [JsonSerializable(typeof(int?))]
    [JsonSerializable(typeof(int))]
    [JsonSerializable(typeof(long?))]
    [JsonSerializable(typeof(long))]
    [JsonSerializable(typeof(decimal?))]
    [JsonSerializable(typeof(decimal))]
    [JsonSerializable(typeof(DateTime))]
    [JsonSerializable(typeof(DateTime?))]
    internal partial class CryptoComSourceGenerationContext : JsonSerializerContext
    {
    }
}
